name: Build and Push Docker Images

on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: "0 0 * * *"

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - id: set-matrix
        run: |
          MATRIX="[]"
          for dir in */; do
            if [ -f "${dir}build-params.ts" ]; then
              PARAMS=$(deno run --allow-read "${dir}build-params.ts")
              MATRIX=$(echo "${MATRIX}" | jq -c ". + (${PARAMS})")
            fi
          done
          echo "matrix=${MATRIX}" >> $GITHUB_OUTPUT

  build-and-push:
    runs-on: ubuntu-latest
    needs: prepare
    strategy:
      matrix: ${{ fromJson(needs.prepare.outputs.matrix) }}
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ./${{ matrix.dir }}
          file: ./${{ matrix.dir }}/Dockerfile
          tags: ${{ matrix.repository }}:${{ matrix.tags }}
          build-args: ${{ matrix.buildArgs }}
