name: Build Image

on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: "0 0 * * *"

jobs:
  set-images:
    runs-on: ubuntu-latest
    outputs:
      dir: ${{ steps.set-images.outputs.dir }}
    steps:
      - uses: actions/checkout@v4
      - name: set-images
        id: set-images
        run: |
          DIRS=$(ls -l | grep '^d' | awk '{print $9}' | jq -R -s -c 'split("\n")[:-1]')
          echo "dir=${DIRS}" >> $GITHUB_OUTPUT
  build-and-push:
    runs-on: ubuntu-latest
    needs: set-images
    strategy:
      matrix:
        dir: ${{ fromJson(needs.set-images.outputs.dir) }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ./${{ matrix.dir }}
          platforms: linux/amd64,linux/arm64
          tags: ogontaro/${{ matrix.dir }}:latest
